<?php

namespace App\Ai\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;
use Stringable;

/**
 * BookTravelItineraryTool
 *
 * Auto-generated by AgentGeneral skill: BookTravelItinerary
 * Original description: Generates a travel itinerary for the given destination.
 * needs_input: True
     * Tags: travel, flights, accommodations
 *
 * Delegates execution to AgentGeneral via HTTP.
 * AgentGeneral matches the skill via FAISS — no generation cost on repeat calls.
 */
class BookTravelItineraryTool implements Tool
{
    public function description(): Stringable|string
    {
        return 'Generates a travel itinerary for the given destination. book travel itinerary travel flights accommodations';
    }

    public function handle(Request $request): Stringable|string
    {
        $response = app(\App\Services\AgentGeneralService::class)->run(
            $request['input'] ?? ''
        );
        return is_array($response) ? (string)($response['result'] ?? '') : (string)$response;
    }

    public function schema(JsonSchema $schema): array
    {
        return [
            'input' => $schema->string()->required(),
        ];
    }
}
