<?php

namespace App\Ai\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;
use Stringable;

/**
 * FindAccommodationOptionsTool
 *
 * Auto-generated by AgentGeneral skill: FindAccommodationOptions
 * Original description: Generates a list of accommodation options for the given destination.
 * needs_input: True
     * Tags: Accommodation, Travel, Destination
 *
 * Delegates execution to AgentGeneral via HTTP.
 * AgentGeneral matches the skill via FAISS — no generation cost on repeat calls.
 */
class FindAccommodationOptionsTool implements Tool
{
    public function description(): Stringable|string
    {
        return 'Generates a list of accommodation options for the given destination. find accommodation options Accommodation Travel Destination search locate get retrieve show display enumerate';
    }

    public function handle(Request $request): Stringable|string
    {
        $response = app(\App\Services\AgentGeneralService::class)->run(
            $request['input'] ?? ''
        );
        return is_array($response) ? (string)($response['result'] ?? '') : (string)$response;
    }

    public function schema(JsonSchema $schema): array
    {
        return [
            'input' => $schema->string()->required(),
        ];
    }
}
