<?php

namespace App\Ai\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;
use Stringable;

/**
 * FindAccommodationsForFiveDaysTool
 *
 * Auto-generated by AgentGeneral skill: FindAccommodationsForFiveDays
 * Original description: Generates a list of accommodations for the given destination for five days.
 * needs_input: True
     * Tags: accommodation, travel, lodging
 *
 * Delegates execution to AgentGeneral via HTTP.
 * AgentGeneral matches the skill via FAISS — no generation cost on repeat calls.
 */
class FindAccommodationsForFiveDaysTool implements Tool
{
    public function description(): Stringable|string
    {
        return 'Generates a list of accommodations for the given destination for five days. find accommodations for five days accommodation travel lodging search locate get retrieve show display enumerate';
    }

    public function handle(Request $request): Stringable|string
    {
        $response = app(\App\Services\AgentGeneralService::class)->run(
            $request['input'] ?? ''
        );
        return is_array($response) ? (string)($response['result'] ?? '') : (string)$response;
    }

    public function schema(JsonSchema $schema): array
    {
        return [
            'input' => $schema->string()->required(),
        ];
    }
}
