<?php

namespace App\Ai\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;
use Stringable;

/**
 * PopularDestinations7DaysTool
 *
 * Auto-generated by AgentGeneral skill: PopularDestinations7Days
 * Original description: Generates a list of popular destinations in Australia for 7 days.
 * needs_input: False
     * Tags: travel, australia, destinations
 *
 * Delegates execution to AgentGeneral via HTTP.
 * AgentGeneral matches the skill via FAISS — no generation cost on repeat calls.
 */
class PopularDestinations7DaysTool implements Tool
{
    public function description(): Stringable|string
    {
        return 'Generates a list of popular destinations in Australia for 7 days. popular destinations7 days travel australia destinations show display enumerate';
    }

    public function handle(Request $request): Stringable|string
    {
        $response = app(\App\Services\AgentGeneralService::class)->run(
            'PopularDestinations7Days'
        );
        return is_array($response) ? (string)($response['result'] ?? '') : (string)$response;
    }

    public function schema(JsonSchema $schema): array
    {
        return [];
    }
}
