<?php

namespace App\Ai\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;
use Stringable;

/**
 * TopTikTokTrendsTool
 *
 * Auto-generated by AgentGeneral skill: TopTikTokTrends
 * Original description: Displays the top trending TikTok videos in Japan.
 * needs_input: True
     * Tags: TikTok, trends, Japan
 *
 * Delegates execution to AgentGeneral via HTTP.
 * AgentGeneral matches the skill via FAISS — no generation cost on repeat calls.
 */
class TopTikTokTrendsTool implements Tool
{
    public function description(): Stringable|string
    {
        return 'Displays the top trending TikTok videos in Japan. top tik tok trends TikTok trends Japan';
    }

    public function handle(Request $request): Stringable|string
    {
        $response = app(\App\Services\AgentGeneralService::class)->run(
            $request['input'] ?? ''
        );
        return is_array($response) ? (string)($response['result'] ?? '') : (string)$response;
    }

    public function schema(JsonSchema $schema): array
    {
        return [
            'input' => $schema->string()->required(),
        ];
    }
}
