<?php

namespace App\Ai\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;
use Stringable;

/**
 * TouristAttractionsInDestinationTool
 *
 * Auto-generated by AgentGeneral skill: TouristAttractionsInDestination
 * Original description: Generates a list of popular tourist attractions in the given destination.
 * needs_input: True
     * Tags: travel, tourism, Uganda, attractions
 *
 * Delegates execution to AgentGeneral via HTTP.
 * AgentGeneral matches the skill via FAISS — no generation cost on repeat calls.
 */
class TouristAttractionsInDestinationTool implements Tool
{
    public function description(): Stringable|string
    {
        return 'Generates a list of popular tourist attractions in the given destination. tourist attractions in destination travel tourism Uganda attractions show display enumerate';
    }

    public function handle(Request $request): Stringable|string
    {
        $response = app(\App\Services\AgentGeneralService::class)->run(
            $request['input'] ?? ''
        );
        return is_array($response) ? (string)($response['result'] ?? '') : (string)$response;
    }

    public function schema(JsonSchema $schema): array
    {
        return [
            'input' => $schema->string()->required(),
        ];
    }
}
