<?php

namespace App\Ai\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Tool;
use Laravel\Ai\Tools\Request;
use Stringable;

/**
 * WorkoutRoutineGeneratorTool
 *
 * Auto-generated by AgentGeneral skill: WorkoutRoutineGenerator
 * Original description: Generates a 10-day workout routine using common exercises.
 * needs_input: False
     * Tags: fitness, exercise, workout
 *
 * Delegates execution to AgentGeneral via HTTP.
 * AgentGeneral matches the skill via FAISS — no generation cost on repeat calls.
 */
class WorkoutRoutineGeneratorTool implements Tool
{
    public function description(): Stringable|string
    {
        return 'Generates a 10-day workout routine using common exercises. workout routine generator fitness exercise workout';
    }

    public function handle(Request $request): Stringable|string
    {
        $response = app(\App\Services\AgentGeneralService::class)->run(
            'WorkoutRoutineGenerator'
        );
        return is_array($response) ? (string)($response['result'] ?? '') : (string)$response;
    }

    public function schema(JsonSchema $schema): array
    {
        return [];
    }
}
